// @generated by schema-rust from an authority-verified bootstrap Interface

pub enum z2VeFa {z2VWD1 , z2VSrR , z2VPep , z2VUkh , z2Va3o , z2VSvv ,} 
pub struct z2VLeK {
    pub field_0: z2VYvZ,
    pub field_1: z2Vb34,
    pub field_2: z2VeFa,
}
pub enum z2VYvZ {z2VL8e , z2VT1m , z2VXu1 , z2VXaz ,} 
pub enum z2Vb34 {z2VNom , z2VVKc , z2VUN4 , z2VcKD , z2Vevy , z2Vd7t ,} 
pub struct z2VWJM {
    pub field_0: Option<z2VYvZ>,
    pub field_1: Option<z2Vb34>,
}
pub struct z2VUen(Vec<z2VLeK>);
impl z2VUen {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: Vec<z2VLeK>) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &Vec<z2VLeK> {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> Vec<z2VLeK> {
        self.0
    }
}
