use signal_cloud::{CAPABILITY_INTERFACE_RUST, CAPABILITY_INTERFACE_SOURCE};

#[test]
fn capability_interface_is_role_free_and_strictly_generated() {
    assert!(
        CAPABILITY_INTERFACE_SOURCE.starts_with("Interface.{1 0 0}\n[]\n{\n  []\n  []\n  []\n  [")
    );
    assert!(CAPABILITY_INTERFACE_SOURCE.contains("Provider.["));
    assert!(CAPABILITY_INTERFACE_SOURCE.contains("Cloudflare"));
    assert!(CAPABILITY_INTERFACE_SOURCE.contains("CapabilityReport.Vector<CapabilityObservation>"));
    assert!(CAPABILITY_INTERFACE_RUST.starts_with(
        "// @generated by schema-rust from an authority-verified bootstrap Interface\n"
    ));
}

#[test]
fn build_uses_one_exact_verified_bootstrap_boundary() {
    let manifest = include_str!("../Cargo.toml");
    let build = include_str!("../build.rs");

    assert!(manifest.contains("34b912a7703f4f9419ceff539aa3804513d1ef28"));
    assert_eq!(manifest.matches("schema-rust =").count(), 1);
    assert_eq!(build.matches("BootstrapInterfaceGeneration").count(), 2);
    assert!(build.contains("BootstrapTransactionAssembler"));
    assert!(build.contains("RustTypePath::try_new"));
}
