// @generated by schema-rust

#[rustfmt::skip]
pub type String = std::string::String;
#[rustfmt::skip]
pub type Integer = u64;
#[rustfmt::skip]
pub type Boolean = bool;
#[rustfmt::skip]
pub type Path = std::string::String;

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
pub use nota::{NotaDecodeError, NotaEncode, NotaSource};

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Observe(Observation);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Validate(Validation);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Observed(ObservationResult);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Validated(ValidationReport);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RequestUnsupported(UnsupportedRequest);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RequestRejected(RejectedRequest);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DomainName(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RecordValue(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct UniformResourceLocator(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct PlanIdentifier(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ProviderAccount(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ZoneIdentifier(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RuleIdentifier(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct HostIdentifier(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ServerType(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ImageName(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct IpAddress(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum Provider {
    Cloudflare,
    GoogleCloud,
    Hetzner,
    DigitalOcean,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum Capability {
    DomainNameSystemRecords,
    RedirectRules,
    CloudHosts,
    Networks,
    Firewalls,
    LoadBalancers,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum CapabilityState {
    NotBuilt,
    Compiled,
    Configured,
    Authorized,
    Unsupported,
    Unauthorized,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum RecordKind {
    AddressV4,
    AddressV6,
    CanonicalName,
    Text,
    MailExchange,
    NameServer,
    Pointer,
    Service,
    CertificateAuthorityAuthorization,
    SecureShellFingerprint,
    TransportLayerSecurityAuthentication,
    UniformResourceIdentifier,
    ServiceBinding,
    HttpsBinding,
    Location,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ProxyMode {
    Direct,
    ProviderProxy,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum RedirectStatus {
    Permanent,
    Temporary,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum PathTreatment {
    Preserve,
    Replace,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum HostStatus {
    Initializing,
    Running,
    Stopped,
    Deleting,
    Unknown,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CapabilityQuery {
    pub provider: Option<Provider>,
    pub capability: Option<Capability>,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CapabilityObservation {
    pub provider: Provider,
    pub capability: Capability,
    pub capability_state: CapabilityState,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CapabilityReport(Vec<CapabilityObservation>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ZoneQuery {
    pub provider: Option<Provider>,
    pub account: Option<ProviderAccount>,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Zone {
    pub provider: Provider,
    pub provider_account: ProviderAccount,
    pub zone_identifier: ZoneIdentifier,
    pub domain_name: DomainName,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ZoneListing(Vec<Zone>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct HostQuery {
    pub provider: Provider,
    pub provider_account: Option<ProviderAccount>,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CloudHost {
    pub provider: Provider,
    pub provider_account: ProviderAccount,
    pub host_identifier: HostIdentifier,
    pub host_name: DomainName,
    pub server_type: ServerType,
    pub image_name: ImageName,
    pub ipv4_address: IpAddress,
    pub host_status: HostStatus,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CloudHostListing(Vec<CloudHost>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DomainNameSystemRecord {
    pub domain_name: DomainName,
    pub record_kind: RecordKind,
    pub record_value: RecordValue,
    pub proxy_mode: ProxyMode,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RecordQuery {
    pub provider: Provider,
    pub domain_name: DomainName,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RecordListing(Vec<DomainNameSystemRecord>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RedirectRule {
    pub domain_name: DomainName,
    pub uniform_resource_locator: UniformResourceLocator,
    pub redirect_status: RedirectStatus,
    pub path_treatment: PathTreatment,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RedirectQuery {
    pub provider: Provider,
    pub domain_name: DomainName,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RedirectListing(Vec<RedirectRule>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DesiredState {
    pub provider: Provider,
    pub domain_name: DomainName,
    pub records: Vec<DomainNameSystemRecord>,
    pub redirects: Vec<RedirectRule>,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Validation(DesiredState);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Plan {
    pub plan_identifier: PlanIdentifier,
    pub provider: Provider,
    pub domain_name: DomainName,
    pub records_to_create: Vec<DomainNameSystemRecord>,
    pub records_to_update: Vec<DomainNameSystemRecord>,
    pub record_names_to_delete: Vec<DomainName>,
    pub redirects_to_create: Vec<RedirectRule>,
    pub redirects_to_update: Vec<RedirectRule>,
    pub redirect_sources_to_delete: Vec<DomainName>,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct PlanQuery(PlanIdentifier);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Observation {
    Capabilities(Capabilities),
    Zones(Zones),
    Records(Records),
    Redirects(Redirects),
    ObserveServers(ObserveServers),
    ObservePlan(ObservePlan),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Capabilities(CapabilityQuery);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Zones(ZoneQuery);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Records(RecordQuery);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Redirects(RedirectQuery);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ObserveServers(HostQuery);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ObservePlan(PlanQuery);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum ObservationResult {
    Capabilities(CapabilityReport),
    Zones(ZoneListing),
    Records(RecordListing),
    Redirects(RedirectListing),
    Servers(CloudHostListing),
    PlanResult(PlanResult),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct PlanResult(Plan);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum FindingSeverity {
    Notice,
    Warning,
    Error,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ValidationFinding {
    pub finding_severity: FindingSeverity,
    pub message: Message,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Message(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ValidationReport(Vec<ValidationFinding>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum UnsupportedReason {
    ProviderNotBuilt,
    ProviderNotCompiled,
    ProviderNotConfigured,
    CapabilityNotCompiled,
    CapabilityNotConfigured,
    CapabilityUnauthorized,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct UnsupportedRequest {
    pub provider: Option<Provider>,
    pub capability: Option<Capability>,
    pub reason: UnsupportedReason,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum RejectionReason {
    InvalidDesiredState,
    PlanExpired,
    ProviderRateLimited,
    ProviderUnavailable,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RejectedRequest(RejectionReason);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Input {
    Observe(Observation),
    Validate(Validation),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Output {
    Observed(ObservationResult),
    Validated(ValidationReport),
    RequestUnsupported(UnsupportedRequest),
    RequestRejected(RejectedRequest),
}

#[rustfmt::skip]
impl Observe {
    pub fn new(payload: Observation) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Observation {
        &self.0
    }
    pub fn into_payload(self) -> Observation {
        self.0
    }
}
#[rustfmt::skip]
impl From<Observation> for Observe {
    fn from(payload: Observation) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Validate {
    pub fn new(payload: Validation) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Validation {
        &self.0
    }
    pub fn into_payload(self) -> Validation {
        self.0
    }
}
#[rustfmt::skip]
impl From<Validation> for Validate {
    fn from(payload: Validation) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Observed {
    pub fn new(payload: ObservationResult) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ObservationResult {
        &self.0
    }
    pub fn into_payload(self) -> ObservationResult {
        self.0
    }
}
#[rustfmt::skip]
impl From<ObservationResult> for Observed {
    fn from(payload: ObservationResult) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Validated {
    pub fn new(payload: ValidationReport) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ValidationReport {
        &self.0
    }
    pub fn into_payload(self) -> ValidationReport {
        self.0
    }
}
#[rustfmt::skip]
impl From<ValidationReport> for Validated {
    fn from(payload: ValidationReport) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RequestUnsupported {
    pub fn new(payload: UnsupportedRequest) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &UnsupportedRequest {
        &self.0
    }
    pub fn into_payload(self) -> UnsupportedRequest {
        self.0
    }
}
#[rustfmt::skip]
impl From<UnsupportedRequest> for RequestUnsupported {
    fn from(payload: UnsupportedRequest) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RequestRejected {
    pub fn new(payload: RejectedRequest) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &RejectedRequest {
        &self.0
    }
    pub fn into_payload(self) -> RejectedRequest {
        self.0
    }
}
#[rustfmt::skip]
impl From<RejectedRequest> for RequestRejected {
    fn from(payload: RejectedRequest) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl DomainName {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for DomainName {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RecordValue {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for RecordValue {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl UniformResourceLocator {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for UniformResourceLocator {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl PlanIdentifier {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for PlanIdentifier {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ProviderAccount {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for ProviderAccount {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ZoneIdentifier {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for ZoneIdentifier {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RuleIdentifier {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for RuleIdentifier {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl HostIdentifier {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for HostIdentifier {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ServerType {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for ServerType {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ImageName {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for ImageName {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl IpAddress {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for IpAddress {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl CapabilityReport {
    pub fn new(payload: Vec<CapabilityObservation>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<CapabilityObservation> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<CapabilityObservation> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<CapabilityObservation>> for CapabilityReport {
    fn from(payload: Vec<CapabilityObservation>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ZoneListing {
    pub fn new(payload: Vec<Zone>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<Zone> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<Zone> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<Zone>> for ZoneListing {
    fn from(payload: Vec<Zone>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl CloudHostListing {
    pub fn new(payload: Vec<CloudHost>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<CloudHost> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<CloudHost> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<CloudHost>> for CloudHostListing {
    fn from(payload: Vec<CloudHost>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RecordListing {
    pub fn new(payload: Vec<DomainNameSystemRecord>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<DomainNameSystemRecord> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<DomainNameSystemRecord> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<DomainNameSystemRecord>> for RecordListing {
    fn from(payload: Vec<DomainNameSystemRecord>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RedirectListing {
    pub fn new(payload: Vec<RedirectRule>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<RedirectRule> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<RedirectRule> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<RedirectRule>> for RedirectListing {
    fn from(payload: Vec<RedirectRule>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Validation {
    pub fn new(payload: DesiredState) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &DesiredState {
        &self.0
    }
    pub fn into_payload(self) -> DesiredState {
        self.0
    }
}
#[rustfmt::skip]
impl From<DesiredState> for Validation {
    fn from(payload: DesiredState) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl PlanQuery {
    pub fn new(payload: PlanIdentifier) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &PlanIdentifier {
        &self.0
    }
    pub fn into_payload(self) -> PlanIdentifier {
        self.0
    }
}
#[rustfmt::skip]
impl From<PlanIdentifier> for PlanQuery {
    fn from(payload: PlanIdentifier) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Capabilities {
    pub fn new(payload: CapabilityQuery) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &CapabilityQuery {
        &self.0
    }
    pub fn into_payload(self) -> CapabilityQuery {
        self.0
    }
}
#[rustfmt::skip]
impl From<CapabilityQuery> for Capabilities {
    fn from(payload: CapabilityQuery) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Zones {
    pub fn new(payload: ZoneQuery) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ZoneQuery {
        &self.0
    }
    pub fn into_payload(self) -> ZoneQuery {
        self.0
    }
}
#[rustfmt::skip]
impl From<ZoneQuery> for Zones {
    fn from(payload: ZoneQuery) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Records {
    pub fn new(payload: RecordQuery) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &RecordQuery {
        &self.0
    }
    pub fn into_payload(self) -> RecordQuery {
        self.0
    }
}
#[rustfmt::skip]
impl From<RecordQuery> for Records {
    fn from(payload: RecordQuery) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Redirects {
    pub fn new(payload: RedirectQuery) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &RedirectQuery {
        &self.0
    }
    pub fn into_payload(self) -> RedirectQuery {
        self.0
    }
}
#[rustfmt::skip]
impl From<RedirectQuery> for Redirects {
    fn from(payload: RedirectQuery) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ObserveServers {
    pub fn new(payload: HostQuery) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &HostQuery {
        &self.0
    }
    pub fn into_payload(self) -> HostQuery {
        self.0
    }
}
#[rustfmt::skip]
impl From<HostQuery> for ObserveServers {
    fn from(payload: HostQuery) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ObservePlan {
    pub fn new(payload: PlanQuery) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &PlanQuery {
        &self.0
    }
    pub fn into_payload(self) -> PlanQuery {
        self.0
    }
}
#[rustfmt::skip]
impl From<PlanQuery> for ObservePlan {
    fn from(payload: PlanQuery) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl PlanResult {
    pub fn new(payload: Plan) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Plan {
        &self.0
    }
    pub fn into_payload(self) -> Plan {
        self.0
    }
}
#[rustfmt::skip]
impl From<Plan> for PlanResult {
    fn from(payload: Plan) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Message {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for Message {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ValidationReport {
    pub fn new(payload: Vec<ValidationFinding>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<ValidationFinding> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<ValidationFinding> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<ValidationFinding>> for ValidationReport {
    fn from(payload: Vec<ValidationFinding>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RejectedRequest {
    pub fn new(payload: RejectionReason) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &RejectionReason {
        &self.0
    }
    pub fn into_payload(self) -> RejectionReason {
        self.0
    }
}
#[rustfmt::skip]
impl From<RejectionReason> for RejectedRequest {
    fn from(payload: RejectionReason) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Observation {
    pub fn capabilities(payload: CapabilityQuery) -> Self {
        Self::Capabilities(Capabilities::new(payload))
    }
    pub fn zones(payload: ZoneQuery) -> Self {
        Self::Zones(Zones::new(payload))
    }
    pub fn records(payload: RecordQuery) -> Self {
        Self::Records(Records::new(payload))
    }
    pub fn redirects(payload: RedirectQuery) -> Self {
        Self::Redirects(Redirects::new(payload))
    }
    pub fn observe_servers(payload: HostQuery) -> Self {
        Self::ObserveServers(ObserveServers::new(payload))
    }
    pub fn observe_plan(payload: PlanQuery) -> Self {
        Self::ObservePlan(ObservePlan::new(payload))
    }
}

#[rustfmt::skip]
impl ObservationResult {
    pub fn capabilities(payload: Vec<CapabilityObservation>) -> Self {
        Self::Capabilities(CapabilityReport::new(payload))
    }
    pub fn zones(payload: Vec<Zone>) -> Self {
        Self::Zones(ZoneListing::new(payload))
    }
    pub fn records(payload: Vec<DomainNameSystemRecord>) -> Self {
        Self::Records(RecordListing::new(payload))
    }
    pub fn redirects(payload: Vec<RedirectRule>) -> Self {
        Self::Redirects(RedirectListing::new(payload))
    }
    pub fn servers(payload: Vec<CloudHost>) -> Self {
        Self::Servers(CloudHostListing::new(payload))
    }
    pub fn plan_result(payload: Plan) -> Self {
        Self::PlanResult(PlanResult::new(payload))
    }
}

#[rustfmt::skip]
impl Input {
    pub fn observe(payload: Observation) -> Self {
        Self::Observe(payload)
    }
    pub fn validate(payload: DesiredState) -> Self {
        Self::Validate(Validation::new(payload))
    }
}

#[rustfmt::skip]
impl Output {
    pub fn observed(payload: ObservationResult) -> Self {
        Self::Observed(payload)
    }
    pub fn validated(payload: Vec<ValidationFinding>) -> Self {
        Self::Validated(ValidationReport::new(payload))
    }
    pub fn request_unsupported(payload: UnsupportedRequest) -> Self {
        Self::RequestUnsupported(payload)
    }
    pub fn request_rejected(payload: RejectionReason) -> Self {
        Self::RequestRejected(RejectedRequest::new(payload))
    }
}

#[rustfmt::skip]
impl From<Capabilities> for Observation {
    fn from(payload: Capabilities) -> Self {
        Self::Capabilities(payload)
    }
}

#[rustfmt::skip]
impl From<Zones> for Observation {
    fn from(payload: Zones) -> Self {
        Self::Zones(payload)
    }
}

#[rustfmt::skip]
impl From<Records> for Observation {
    fn from(payload: Records) -> Self {
        Self::Records(payload)
    }
}

#[rustfmt::skip]
impl From<Redirects> for Observation {
    fn from(payload: Redirects) -> Self {
        Self::Redirects(payload)
    }
}

#[rustfmt::skip]
impl From<ObserveServers> for Observation {
    fn from(payload: ObserveServers) -> Self {
        Self::ObserveServers(payload)
    }
}

#[rustfmt::skip]
impl From<ObservePlan> for Observation {
    fn from(payload: ObservePlan) -> Self {
        Self::ObservePlan(payload)
    }
}

#[rustfmt::skip]
impl From<CapabilityReport> for ObservationResult {
    fn from(payload: CapabilityReport) -> Self {
        Self::Capabilities(payload)
    }
}

#[rustfmt::skip]
impl From<ZoneListing> for ObservationResult {
    fn from(payload: ZoneListing) -> Self {
        Self::Zones(payload)
    }
}

#[rustfmt::skip]
impl From<RecordListing> for ObservationResult {
    fn from(payload: RecordListing) -> Self {
        Self::Records(payload)
    }
}

#[rustfmt::skip]
impl From<RedirectListing> for ObservationResult {
    fn from(payload: RedirectListing) -> Self {
        Self::Redirects(payload)
    }
}

#[rustfmt::skip]
impl From<CloudHostListing> for ObservationResult {
    fn from(payload: CloudHostListing) -> Self {
        Self::Servers(payload)
    }
}

#[rustfmt::skip]
impl From<PlanResult> for ObservationResult {
    fn from(payload: PlanResult) -> Self {
        Self::PlanResult(payload)
    }
}

#[rustfmt::skip]
impl From<Observation> for Input {
    fn from(payload: Observation) -> Self {
        Self::Observe(payload)
    }
}

#[rustfmt::skip]
impl From<Validation> for Input {
    fn from(payload: Validation) -> Self {
        Self::Validate(payload)
    }
}

#[rustfmt::skip]
impl From<ObservationResult> for Output {
    fn from(payload: ObservationResult) -> Self {
        Self::Observed(payload)
    }
}

#[rustfmt::skip]
impl From<ValidationReport> for Output {
    fn from(payload: ValidationReport) -> Self {
        Self::Validated(payload)
    }
}

#[rustfmt::skip]
impl From<UnsupportedRequest> for Output {
    fn from(payload: UnsupportedRequest) -> Self {
        Self::RequestUnsupported(payload)
    }
}

#[rustfmt::skip]
impl From<RejectedRequest> for Output {
    fn from(payload: RejectedRequest) -> Self {
        Self::RequestRejected(payload)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Input {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Input {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Output {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Output {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
pub mod short_header {
    pub const INPUT_OBSERVE: u64 = 0x0000000000000000;
    pub const INPUT_VALIDATE: u64 = 0x0001000000000000;
    pub const OUTPUT_OBSERVED: u64 = 0x0100000000000000;
    pub const OUTPUT_VALIDATED: u64 = 0x0101000000000000;
    pub const OUTPUT_REQUEST_UNSUPPORTED: u64 = 0x0102000000000000;
    pub const OUTPUT_REQUEST_REJECTED: u64 = 0x0103000000000000;
}

#[rustfmt::skip]
const SIGNAL_SHORT_HEADER_BYTE_COUNT: usize = 8;
#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum SignalFrameError {
    ArchiveEncode,
    ArchiveDecode,
    FrameTooShort { found: usize },
    UnknownHeader { root_enum: &'static str, header: u64 },
    HeaderMismatch { expected: u64, found: u64 },
}
#[rustfmt::skip]
impl std::fmt::Display for SignalFrameError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ArchiveEncode => formatter.write_str("failed to encode rkyv archive"),
            Self::ArchiveDecode => formatter.write_str("failed to decode rkyv archive"),
            Self::FrameTooShort { found } => {
                write!(formatter, "signal frame too short: {found} bytes")
            }
            Self::UnknownHeader { root_enum, header } => {
                write!(formatter, "unknown {root_enum} short header 0x{header:016X}")
            }
            Self::HeaderMismatch { expected, found } => {
                write!(
                    formatter,
                    "decoded payload header mismatch: expected 0x{expected:016X}, found 0x{found:016X}"
                )
            }
        }
    }
}
#[rustfmt::skip]
impl std::error::Error for SignalFrameError {}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum InputRoute {
    Observe,
    Validate,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum OutputRoute {
    Observed,
    Validated,
    RequestUnsupported,
    RequestRejected,
}

#[rustfmt::skip]
impl Input {
    pub fn route(&self) -> InputRoute {
        match self {
            Self::Observe(_) => InputRoute::Observe,
            Self::Validate(_) => InputRoute::Validate,
        }
    }
    pub fn short_header(&self) -> u64 {
        match self {
            Self::Observe(_) => short_header::INPUT_OBSERVE,
            Self::Validate(_) => short_header::INPUT_VALIDATE,
        }
    }
    pub fn route_from_short_header(header: u64) -> Result<InputRoute, SignalFrameError> {
        match header {
            short_header::INPUT_OBSERVE => Ok(InputRoute::Observe),
            short_header::INPUT_VALIDATE => Ok(InputRoute::Validate),
            _ => {
                Err(SignalFrameError::UnknownHeader {
                    root_enum: "Input",
                    header,
                })
            }
        }
    }
    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(
            SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len(),
        );
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }
    pub fn decode_signal_frame(
        frame: &[u8],
    ) -> Result<(InputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort {
                found: frame.len(),
            });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<
            Self,
            rkyv::rancor::Error,
        >(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch {
                expected,
                found: header,
            });
        }
        Ok((route, value))
    }
}

#[rustfmt::skip]
impl Output {
    pub fn route(&self) -> OutputRoute {
        match self {
            Self::Observed(_) => OutputRoute::Observed,
            Self::Validated(_) => OutputRoute::Validated,
            Self::RequestUnsupported(_) => OutputRoute::RequestUnsupported,
            Self::RequestRejected(_) => OutputRoute::RequestRejected,
        }
    }
    pub fn short_header(&self) -> u64 {
        match self {
            Self::Observed(_) => short_header::OUTPUT_OBSERVED,
            Self::Validated(_) => short_header::OUTPUT_VALIDATED,
            Self::RequestUnsupported(_) => short_header::OUTPUT_REQUEST_UNSUPPORTED,
            Self::RequestRejected(_) => short_header::OUTPUT_REQUEST_REJECTED,
        }
    }
    pub fn route_from_short_header(
        header: u64,
    ) -> Result<OutputRoute, SignalFrameError> {
        match header {
            short_header::OUTPUT_OBSERVED => Ok(OutputRoute::Observed),
            short_header::OUTPUT_VALIDATED => Ok(OutputRoute::Validated),
            short_header::OUTPUT_REQUEST_UNSUPPORTED => {
                Ok(OutputRoute::RequestUnsupported)
            }
            short_header::OUTPUT_REQUEST_REJECTED => Ok(OutputRoute::RequestRejected),
            _ => {
                Err(SignalFrameError::UnknownHeader {
                    root_enum: "Output",
                    header,
                })
            }
        }
    }
    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(
            SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len(),
        );
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }
    pub fn decode_signal_frame(
        frame: &[u8],
    ) -> Result<(OutputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort {
                found: frame.len(),
            });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<
            Self,
            rkyv::rancor::Error,
        >(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch {
                expected,
                found: header,
            });
        }
        Ok((route, value))
    }
}

#[rustfmt::skip]
impl signal_frame::RequestPayload for Input {}
#[rustfmt::skip]
impl signal_frame::SignalOperationHeads for Input {
    const HEADS: &'static [&'static str] = &["Observe", "Validate"];
}
#[rustfmt::skip]
impl signal_frame::LogVariant for Input {
    fn log_variant(&self) -> u64 {
        self.short_header()
    }
}
#[rustfmt::skip]
pub type Frame = signal_frame::ExchangeFrame<Input, Output>;
#[rustfmt::skip]
pub type FrameBody = signal_frame::ExchangeFrameBody<Input, Output>;
#[rustfmt::skip]
pub type Request = signal_frame::Request<Input>;
#[rustfmt::skip]
pub type ReplyEnvelope = signal_frame::Reply<Output>;
#[rustfmt::skip]
pub type RequestBuilder = signal_frame::RequestBuilder<Input>;
#[rustfmt::skip]
impl Input {
    pub fn into_frame(self, exchange: signal_frame::ExchangeIdentifier) -> Frame {
        let short_header = signal_frame::ShortHeader::new(self.short_header());
        let request = signal_frame::Request::from_payload(self);
        Frame::with_short_header(
            short_header,
            FrameBody::Request {
                exchange,
                request,
            },
        )
    }
}
#[rustfmt::skip]
impl Output {
    pub fn into_reply_frame(self, exchange: signal_frame::ExchangeIdentifier) -> Frame {
        let short_header = signal_frame::ShortHeader::new(self.short_header());
        let reply = signal_frame::Reply::committed(
            signal_frame::NonEmpty::single(signal_frame::SubReply::Ok(self)),
        );
        Frame::with_short_header(
            short_header,
            FrameBody::Reply {
                exchange,
                reply,
            },
        )
    }
}
