// @generated by schema-rust-next

#[rustfmt::skip]
pub type String = std::string::String;
#[rustfmt::skip]
pub type Integer = u64;
#[rustfmt::skip]
pub type Boolean = bool;
#[rustfmt::skip]
pub type Path = std::string::String;

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
pub use nota_next::{NotaDecode, NotaDecodeError, NotaEncode, NotaSource};

#[rustfmt::skip]
pub type Observe = Observation;

#[rustfmt::skip]
pub type Validate = Validation;

#[rustfmt::skip]
pub type Observed = ObservationResult;

#[rustfmt::skip]
pub type Validated = ValidationReport;

#[rustfmt::skip]
pub type RequestUnsupported = UnsupportedRequest;

#[rustfmt::skip]
pub type RequestRejected = RejectedRequest;

#[rustfmt::skip]
pub type DomainName = String;

#[rustfmt::skip]
pub type RecordValue = String;

#[rustfmt::skip]
pub type UniformResourceLocator = String;

#[rustfmt::skip]
pub type PlanIdentifier = String;

#[rustfmt::skip]
pub type ProviderAccount = String;

#[rustfmt::skip]
pub type ZoneIdentifier = String;

#[rustfmt::skip]
pub type RuleIdentifier = String;

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Provider {
    Cloudflare,
    GoogleCloud,
    Hetzner,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Capability {
    DomainNameSystemRecords,
    RedirectRules,
    CloudHosts,
    Networks,
    Firewalls,
    LoadBalancers,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum CapabilityState {
    NotBuilt,
    Compiled,
    Configured,
    Authorized,
    Unsupported,
    Unauthorized,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum RecordKind {
    AddressV4,
    AddressV6,
    CanonicalName,
    Text,
    MailExchange,
    NameServer,
    Pointer,
    Service,
    CertificateAuthorityAuthorization,
    SecureShellFingerprint,
    TransportLayerSecurityAuthentication,
    UniformResourceIdentifier,
    ServiceBinding,
    HttpsBinding,
    Location,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum ProxyMode {
    Direct,
    ProviderProxy,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum RedirectStatus {
    Permanent,
    Temporary,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum PathTreatment {
    Preserve,
    Replace,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CapabilityQuery {
    pub provider: Option<Provider>,
    pub capability: Option<Capability>,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CapabilityObservation {
    pub provider: Provider,
    pub capability: Capability,
    pub capability_state: CapabilityState,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CapabilityReport(pub Vec<CapabilityObservation>);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ZoneQuery {
    pub provider: Option<Provider>,
    pub account: Option<ProviderAccount>,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Zone {
    pub provider: Provider,
    pub provider_account: ProviderAccount,
    pub zone_identifier: ZoneIdentifier,
    pub domain_name: DomainName,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ZoneListing(pub Vec<Zone>);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DomainNameSystemRecord {
    pub domain_name: DomainName,
    pub record_kind: RecordKind,
    pub record_value: RecordValue,
    pub proxy_mode: ProxyMode,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RecordQuery {
    pub provider: Provider,
    pub domain_name: DomainName,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RecordListing(pub Vec<DomainNameSystemRecord>);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RedirectRule {
    pub domain_name: DomainName,
    pub uniform_resource_locator: UniformResourceLocator,
    pub redirect_status: RedirectStatus,
    pub path_treatment: PathTreatment,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RedirectQuery {
    pub provider: Provider,
    pub domain_name: DomainName,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RedirectListing(pub Vec<RedirectRule>);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DesiredState {
    pub provider: Provider,
    pub domain_name: DomainName,
    pub records: Vec<DomainNameSystemRecord>,
    pub redirects: Vec<RedirectRule>,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Validation(pub DesiredState);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Plan {
    pub plan_identifier: PlanIdentifier,
    pub provider: Provider,
    pub domain_name: DomainName,
    pub records_to_create: Vec<DomainNameSystemRecord>,
    pub records_to_update: Vec<DomainNameSystemRecord>,
    pub record_names_to_delete: Vec<DomainName>,
    pub redirects_to_create: Vec<RedirectRule>,
    pub redirects_to_update: Vec<RedirectRule>,
    pub redirect_sources_to_delete: Vec<DomainName>,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct PlanQuery(pub PlanIdentifier);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Observation {
    Capabilities(Capabilities),
    Zones(Zones),
    Records(Records),
    Redirects(Redirects),
    ObservePlan(ObservePlan),
}

#[rustfmt::skip]
pub type Capabilities = CapabilityQuery;

#[rustfmt::skip]
pub type Zones = ZoneQuery;

#[rustfmt::skip]
pub type Records = RecordQuery;

#[rustfmt::skip]
pub type Redirects = RedirectQuery;

#[rustfmt::skip]
pub type ObservePlan = PlanQuery;

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum ObservationResult {
    Capabilities(CapabilityReport),
    Zones(ZoneListing),
    Records(RecordListing),
    Redirects(RedirectListing),
    PlanResult(PlanResult),
}

#[rustfmt::skip]
pub type PlanResult = Plan;

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum FindingSeverity {
    Notice,
    Warning,
    Error,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ValidationFinding {
    pub finding_severity: FindingSeverity,
    pub message: Message,
}

#[rustfmt::skip]
pub type Message = String;

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ValidationReport(pub Vec<ValidationFinding>);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum UnsupportedReason {
    ProviderNotBuilt,
    ProviderNotCompiled,
    ProviderNotConfigured,
    CapabilityNotCompiled,
    CapabilityNotConfigured,
    CapabilityUnauthorized,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct UnsupportedRequest {
    pub provider: Option<Provider>,
    pub capability: Option<Capability>,
    pub reason: UnsupportedReason,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum RejectionReason {
    InvalidDesiredState,
    PlanExpired,
    ProviderRateLimited,
    ProviderUnavailable,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RejectedRequest(pub RejectionReason);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Input {
    Observe(Observe),
    Validate(Validate),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Output {
    Observed(Observed),
    Validated(Validated),
    RequestUnsupported(RequestUnsupported),
    RequestRejected(RequestRejected),
}

#[rustfmt::skip]
impl CapabilityReport {
    pub fn new(payload: Vec<CapabilityObservation>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<CapabilityObservation> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<CapabilityObservation> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<CapabilityObservation>> for CapabilityReport {
    fn from(payload: Vec<CapabilityObservation>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ZoneListing {
    pub fn new(payload: Vec<Zone>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<Zone> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<Zone> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<Zone>> for ZoneListing {
    fn from(payload: Vec<Zone>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RecordListing {
    pub fn new(payload: Vec<DomainNameSystemRecord>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<DomainNameSystemRecord> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<DomainNameSystemRecord> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<DomainNameSystemRecord>> for RecordListing {
    fn from(payload: Vec<DomainNameSystemRecord>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RedirectListing {
    pub fn new(payload: Vec<RedirectRule>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<RedirectRule> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<RedirectRule> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<RedirectRule>> for RedirectListing {
    fn from(payload: Vec<RedirectRule>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Validation {
    pub fn new(payload: DesiredState) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &DesiredState {
        &self.0
    }
    pub fn into_payload(self) -> DesiredState {
        self.0
    }
}
#[rustfmt::skip]
impl From<DesiredState> for Validation {
    fn from(payload: DesiredState) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl PlanQuery {
    pub fn new(payload: PlanIdentifier) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &PlanIdentifier {
        &self.0
    }
    pub fn into_payload(self) -> PlanIdentifier {
        self.0
    }
}
#[rustfmt::skip]
impl From<PlanIdentifier> for PlanQuery {
    fn from(payload: PlanIdentifier) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ValidationReport {
    pub fn new(payload: Vec<ValidationFinding>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<ValidationFinding> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<ValidationFinding> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<ValidationFinding>> for ValidationReport {
    fn from(payload: Vec<ValidationFinding>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RejectedRequest {
    pub fn new(payload: RejectionReason) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &RejectionReason {
        &self.0
    }
    pub fn into_payload(self) -> RejectionReason {
        self.0
    }
}
#[rustfmt::skip]
impl From<RejectionReason> for RejectedRequest {
    fn from(payload: RejectionReason) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Observation {
    pub fn capabilities(payload: Capabilities) -> Self {
        Self::Capabilities(payload)
    }
    pub fn zones(payload: Zones) -> Self {
        Self::Zones(payload)
    }
    pub fn records(payload: Records) -> Self {
        Self::Records(payload)
    }
    pub fn redirects(payload: Redirects) -> Self {
        Self::Redirects(payload)
    }
    pub fn observe_plan(payload: ObservePlan) -> Self {
        Self::ObservePlan(payload)
    }
}

#[rustfmt::skip]
impl ObservationResult {
    pub fn capabilities(payload: Vec<CapabilityObservation>) -> Self {
        Self::Capabilities(CapabilityReport::new(payload))
    }
    pub fn zones(payload: Vec<Zone>) -> Self {
        Self::Zones(ZoneListing::new(payload))
    }
    pub fn records(payload: Vec<DomainNameSystemRecord>) -> Self {
        Self::Records(RecordListing::new(payload))
    }
    pub fn redirects(payload: Vec<RedirectRule>) -> Self {
        Self::Redirects(RedirectListing::new(payload))
    }
    pub fn plan_result(payload: PlanResult) -> Self {
        Self::PlanResult(payload)
    }
}

#[rustfmt::skip]
impl Input {
    pub fn observe(payload: Observe) -> Self {
        Self::Observe(payload)
    }
    pub fn validate(payload: Validate) -> Self {
        Self::Validate(payload)
    }
}

#[rustfmt::skip]
impl Output {
    pub fn observed(payload: Observed) -> Self {
        Self::Observed(payload)
    }
    pub fn validated(payload: Validated) -> Self {
        Self::Validated(payload)
    }
    pub fn request_unsupported(payload: RequestUnsupported) -> Self {
        Self::RequestUnsupported(payload)
    }
    pub fn request_rejected(payload: RequestRejected) -> Self {
        Self::RequestRejected(payload)
    }
}

#[rustfmt::skip]
impl From<CapabilityReport> for ObservationResult {
    fn from(payload: CapabilityReport) -> Self {
        Self::Capabilities(payload)
    }
}

#[rustfmt::skip]
impl From<ZoneListing> for ObservationResult {
    fn from(payload: ZoneListing) -> Self {
        Self::Zones(payload)
    }
}

#[rustfmt::skip]
impl From<RecordListing> for ObservationResult {
    fn from(payload: RecordListing) -> Self {
        Self::Records(payload)
    }
}

#[rustfmt::skip]
impl From<RedirectListing> for ObservationResult {
    fn from(payload: RedirectListing) -> Self {
        Self::Redirects(payload)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl Provider {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl Capability {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl CapabilityState {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl RecordKind {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl ProxyMode {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl RedirectStatus {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl PathTreatment {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl CapabilityQuery {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl CapabilityObservation {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl CapabilityReport {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl ZoneQuery {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl Zone {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl ZoneListing {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl DomainNameSystemRecord {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl RecordQuery {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl RecordListing {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl RedirectRule {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl RedirectQuery {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl RedirectListing {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl DesiredState {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl Validation {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl Plan {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl PlanQuery {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl Observation {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl ObservationResult {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl FindingSeverity {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl ValidationFinding {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl ValidationReport {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl UnsupportedReason {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl UnsupportedRequest {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl RejectionReason {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl RejectedRequest {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl Input {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Input {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Input {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl Output {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Output {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Output {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
pub mod short_header {
    pub const INPUT_OBSERVE: u64 = 0x0000000000000000;
    pub const INPUT_VALIDATE: u64 = 0x0001000000000000;
    pub const OUTPUT_OBSERVED: u64 = 0x0100000000000000;
    pub const OUTPUT_VALIDATED: u64 = 0x0101000000000000;
    pub const OUTPUT_REQUEST_UNSUPPORTED: u64 = 0x0102000000000000;
    pub const OUTPUT_REQUEST_REJECTED: u64 = 0x0103000000000000;
}

#[rustfmt::skip]
const SIGNAL_SHORT_HEADER_BYTE_COUNT: usize = 8;
#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum SignalFrameError {
    ArchiveEncode,
    ArchiveDecode,
    FrameTooShort { found: usize },
    UnknownHeader { root_enum: &'static str, header: u64 },
    HeaderMismatch { expected: u64, found: u64 },
}
#[rustfmt::skip]
impl std::fmt::Display for SignalFrameError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ArchiveEncode => formatter.write_str("failed to encode rkyv archive"),
            Self::ArchiveDecode => formatter.write_str("failed to decode rkyv archive"),
            Self::FrameTooShort { found } => {
                write!(formatter, "signal frame too short: {found} bytes")
            }
            Self::UnknownHeader { root_enum, header } => {
                write!(formatter, "unknown {root_enum} short header 0x{header:016X}")
            }
            Self::HeaderMismatch { expected, found } => {
                write!(
                    formatter,
                    "decoded payload header mismatch: expected 0x{expected:016X}, found 0x{found:016X}"
                )
            }
        }
    }
}
#[rustfmt::skip]
impl std::error::Error for SignalFrameError {}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum InputRoute {
    Observe,
    Validate,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum OutputRoute {
    Observed,
    Validated,
    RequestUnsupported,
    RequestRejected,
}

#[rustfmt::skip]
impl Input {
    pub fn route(&self) -> InputRoute {
        match self {
            Self::Observe(_) => InputRoute::Observe,
            Self::Validate(_) => InputRoute::Validate,
        }
    }
    pub fn short_header(&self) -> u64 {
        match self {
            Self::Observe(_) => short_header::INPUT_OBSERVE,
            Self::Validate(_) => short_header::INPUT_VALIDATE,
        }
    }
    pub fn route_from_short_header(header: u64) -> Result<InputRoute, SignalFrameError> {
        match header {
            short_header::INPUT_OBSERVE => Ok(InputRoute::Observe),
            short_header::INPUT_VALIDATE => Ok(InputRoute::Validate),
            _ => {
                Err(SignalFrameError::UnknownHeader {
                    root_enum: "Input",
                    header,
                })
            }
        }
    }
    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(
            SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len(),
        );
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }
    pub fn decode_signal_frame(
        frame: &[u8],
    ) -> Result<(InputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort {
                found: frame.len(),
            });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<
            Self,
            rkyv::rancor::Error,
        >(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch {
                expected,
                found: header,
            });
        }
        Ok((route, value))
    }
}

#[rustfmt::skip]
impl Output {
    pub fn route(&self) -> OutputRoute {
        match self {
            Self::Observed(_) => OutputRoute::Observed,
            Self::Validated(_) => OutputRoute::Validated,
            Self::RequestUnsupported(_) => OutputRoute::RequestUnsupported,
            Self::RequestRejected(_) => OutputRoute::RequestRejected,
        }
    }
    pub fn short_header(&self) -> u64 {
        match self {
            Self::Observed(_) => short_header::OUTPUT_OBSERVED,
            Self::Validated(_) => short_header::OUTPUT_VALIDATED,
            Self::RequestUnsupported(_) => short_header::OUTPUT_REQUEST_UNSUPPORTED,
            Self::RequestRejected(_) => short_header::OUTPUT_REQUEST_REJECTED,
        }
    }
    pub fn route_from_short_header(
        header: u64,
    ) -> Result<OutputRoute, SignalFrameError> {
        match header {
            short_header::OUTPUT_OBSERVED => Ok(OutputRoute::Observed),
            short_header::OUTPUT_VALIDATED => Ok(OutputRoute::Validated),
            short_header::OUTPUT_REQUEST_UNSUPPORTED => {
                Ok(OutputRoute::RequestUnsupported)
            }
            short_header::OUTPUT_REQUEST_REJECTED => Ok(OutputRoute::RequestRejected),
            _ => {
                Err(SignalFrameError::UnknownHeader {
                    root_enum: "Output",
                    header,
                })
            }
        }
    }
    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(
            SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len(),
        );
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }
    pub fn decode_signal_frame(
        frame: &[u8],
    ) -> Result<(OutputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort {
                found: frame.len(),
            });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<
            Self,
            rkyv::rancor::Error,
        >(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch {
                expected,
                found: header,
            });
        }
        Ok((route, value))
    }
}
